# This is a sample YAML configuration for sending data to
# a production Honeycomb dataset using OTel.
# Note that you must specify HONEYCOMB_API_KEY in your environment
# or --apikey on the command line to authenticate with Honeycomb.
telemetry:
  host: "api.honeycomb.io:443"
  services:
    - "stargate"
    - "apollo"
    - "gemini"
    - "mercury"
    - "artemis"
    - "pioneer"
    - "frontiers"
format:
  depth: 6
  nspans: 100
  tracetime: 5s
quantity:
  tps: 100
  tracecount: 2000
  ramptime: 1s
output:
  sender: otel
  protocol: grpc
global:
  loglevel: warn
fields:
  # simulate URLs for 10 services, each of which has 10 endpoints
  http.url:
    /u10,10
    # generate status codes where 10% are 400s and .1% are 500s
  http.status: /st10,0.1
