name: "Validate PR Title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate Licenses
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: verify licenses
        id: verifyLicenses
        continue-on-error: true
        run: make verify-licenses
      # When the previous step fails, the workflow would normally stop. By adding this
      # condition you can continue the execution with the populated error message.
      - if: ${{ always() && (steps.verifyLicenses.outcome == 'failure') }}
        name: "📝 Add PR comment about updating licenses"
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-licenses-not-updated
          message: |
            Thank you for contributing to the project! 🎉

            We require all licenses of dependencies to be included.

            You should run `make update-licenses` locally to verify that all licenses are included and include
            the updated files in your PR.

            Once you update the repo, this workflow will re-run automatically and validate the updated title.

            Details:

            ```
            ${{ steps.verifyLicenses.outputs.error_message }}
            ```
      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.verifyLicenses.outcome == 'success' }}
        name: "❌ Delete PR comment after licenses have been updated"
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-licenses-not-updated
          delete: true
